spring:
  profiles:
    active: dev
  application:
    name: UTMP
  datasource:
   url: jdbc:mysql://localhost:3306/user?characterEncoding=utf8&useSSL=true&serverTimezone=UTC
   username: root
   password: 123456
   driver-class-name: com.mysql.jdbc.Drive
logging:
  level: 
   root: info

    